### ISSUE TITLE
building

### ISSUE THREAD

**Issue by janeblower** [janeblower/amneziawg-openwrt#2]
> @janeblower Привет. Ты смог собрать амнезию вместе с snapshot opewnrt из исходников?. Не получается нифига((. Именно kmod-amnezia пакет
> 
> https://gist.github.com/Alexey71/df3348722b322f1bd3569223f59186da 

 _Originally posted by @Alexey71 in [b226be4](https://github.com/janeblower/amneziawg-openwrt/commit/b226be453300bb5b46c6bc8748a94c4c70c2a016#commitcomment-150706682)_

**Comment by janeblower** [comment]
@Alexey71
Оно там как-то по-уебански сделано, что не подтягивает зависимости при сборке - кмоды библиотек шифрования.
Моё решение - включи в кмодах обычный Wireguard, он подтянет нужные зависимости и всё сбилдится.

**Comment by Alexey71** [comment]
> @Alexey71 Оно там как-то по-уебански сделано, что не подтягивает зависимости при сборке - кмоды библиотек шифрования. Моё решение - включи в кмодах обычный Wireguard, он подтянет нужные зависимости и всё сбилдится.

Спасибо, включил пакет kmod-wireguard чтобы собирало как M, и амнезия собралась.
